- name: Create BELK + ZooKeeper + Kafka disks(s) and instance(s) cluster
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    state: active
    machine_type: n1-standard-1
    elastic_hosts:
      - elastic01
#      - elastic02
#      - elastic03
    kibana_host:
      - kibana01
    logstash_hosts:
      - logstash01
#      - logstash02
    zookeeper_hosts:
      - zookeeper01
#      - zookeeper02
#      - zookeeper03
    kafka_hosts:
      - kafka01
 #     - kafka02
 #     - kafka03
    beat_hosts:
      - beat01
    elk_disk_type: pd-ssd
    elk_disk_size: 500

    zone: europe-west1

  tasks:
####################
# ELASTICSEARCH NODES
####################
    - name: Launch elastic instances
      gce:
          instance_names: "{{ elastic_hosts|join(',') }}"
          machine_type: "{{ machine_type }}"
          image: centos-7
          tags: elastic
          zone: "{{ zone }}-b"
          state: "{{ state }}"
      register: gce

    - name: Add host to elastic group
      add_host: hostname={{ item.public_ip }} groupname=elastic
      with_items: "{{gce.instance_data | default({})}}"

    - name: Create elastic disks
      gce_pd:
          name: "{{ item }}-data"
          instance_name: "{{ item }}"
          size_gb: "{{ elk_disk_size }}"
          disk_type: "{{ elk_disk_type }}"
          zone: "{{ zone }}-b"
          mode: READ_WRITE
          state: "{{ state }}"
      with_items: "{{elastic_hosts}}"

    - name: Wait for SSH to come up on elastic cluster
      wait_for: host={{ item.public_ip }} port=22 delay=10 timeout=60
      with_items: "{{gce.instance_data | default({})}}"
      when: gce.instance_data is defined

# ####################
# # KIBANA NODES
# ####################
#     - name: Launch kibana instances
#       gce:
#           instance_names: "{{ kibana_host|join(',') }}"
#           machine_type: "{{ machine_type }}"
#           image: centos-7
#           tags: kibana
#           zone: "{{ zone }}-b"
#           state: "{{ state }}"
#       register: gce

#     - name: Add kibana hosts to kibana group
#       add_host: hostname={{ item.public_ip }} groupname=kibana
#       with_items: "{{gce.instance_data | default({})}}"
# ####################
# # LOGSTASH NODES
# ####################
#     - name: Launch logstash instances
#       gce:
#           instance_names: "{{ logstash_hosts|join(',') }}"
#           machine_type: "{{ machine_type }}"
#           image: centos-7
#           tags: logstash
#           zone: "{{ zone }}-b"
#           state: "{{ state }}"
#       register: gce

#     - name: Add logstash hosts to logstash group
#       add_host: hostname={{ item.public_ip }} groupname=logstash
#       with_items: "{{gce.instance_data | default({})}}"
# ####################
# # ZOOKEEPER NODES
# ####################
#     - name: Launch ZooKeeper instances
#       gce:
#           instance_names: "{{ zookeeper_hosts|join(',') }}"
#           machine_type: "{{ machine_type }}"
#           image: centos-7
#           tags: zookeeper
#           zone: "{{ zone }}-b"
#           state: "{{ state }}"
#       register: gce

#     - name: Add Zookeeper hosts to zookeeper group
#       add_host: hostname={{ item.public_ip }} groupname=zookeeper
#       with_items: "{{gce.instance_data | default({})}}"
# ####################
# # KAFKA NODES
# ####################
#     - name: Launch Kafka instances
#       gce:
#           instance_names: "{{ kafka_hosts|join(',') }}"
#           machine_type: "{{ machine_type }}"
#           image: centos-7
#           tags: kafka
#           zone: "{{ zone }}-b"
#           state: "{{ state }}"
#       register: gce

#     - name: Add kafka hosts to kafka group
#       add_host: hostname={{ item.public_ip }} groupname=kafka
#       with_items: "{{gce.instance_data | default({})}}"
# ####################
# # BEATS NODES
# ####################
#     - name: Launch Beats instances
#       gce:
#           instance_names: "{{ beat_hosts|join(',') }}"
#           machine_type: "{{ machine_type }}"
#           image: centos-7
#           tags: beats
#           zone: "{{ zone }}-b"
#           state: "{{ state }}"
#       register: gce

#     - name: Add beat host to beats group
#       add_host: hostname={{ item.public_ip }} groupname=beats
#       with_items: "{{gce.instance_data | default({})}}"
# ####################
# ####################


####################
# ELASTICSEARCH NODES
####################
- name: Setup elasticsearch instance(s)
  hosts: elastic
  become: true
  vars:
    sysctl:
    - name: vm.dirty_ratio
      value: 5
    - name: vm.dirty_background_ratio
      value: 2
    - name: vm.swappiness
      value: 1
    volumes:
    - name: data
      type: ""
    mount_point: /data
  roles:
    - install_dependencies
    - install_elastic
