- name: install the epel rpm
  yum: name=epel-release

- name: Check FS
  shell: mount | grep /dev/sdb
  ignore_errors: yes
  register: fs_mounted

- name: Create XFS filesystem on data device
  filesystem: fstype=xfs dev=/dev/sdb force=yes
  when: fs_mounted|failed

- name: Mount XFS filesystem
  mount: name={{ mount_point }} src=/dev/sdb fstype=xfs state=mounted

- name: Check FS
  shell: mount | grep /dev/sdb
  ignore_errors: yes
  register: fs_mounted

- name: Set sysctl parameters
  sysctl: name={{item.name}} value={{item.value}} state=present sysctl_set=yes reload=yes
  with_items: "{{sysctl}}"