- name: disable selinux (online)
  selinux:
    state: disabled

- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent
- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

# - name: install the epel rpm
#   yum: name=epel-release

- name: import Elastic GPG-KEY
  shell: rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: upload elastic repo
  copy:
    src: "{{elastic_repo}}"
    dest: "{{yum_repos_d}}"
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r"

# - name: install nano
#   package:
#     name: "nano"
#     state: present